

INSERT INTO `origin_box` VALUES ('0', 'Australia');
INSERT INTO `origin_box` VALUES ('0', 'Austria');
INSERT INTO `origin_box` VALUES ('0', 'Barbados');
INSERT INTO `origin_box` VALUES ('0', 'Belgium');
INSERT INTO `origin_box` VALUES ('0', 'China');
INSERT INTO `origin_box` VALUES ('0', 'Cuba');
INSERT INTO `origin_box` VALUES ('0', 'Czech Republic');
INSERT INTO `origin_box` VALUES ('0', 'Denmark');
INSERT INTO `origin_box` VALUES ('0', 'Dominica, Cuba');
INSERT INTO `origin_box` VALUES ('0', 'England');
INSERT INTO `origin_box` VALUES ('0', 'Finland');
INSERT INTO `origin_box` VALUES ('0', 'France');
INSERT INTO `origin_box` VALUES ('0', 'Germany');
INSERT INTO `origin_box` VALUES ('0', 'Ireland');
INSERT INTO `origin_box` VALUES ('0', 'Italy');
INSERT INTO `origin_box` VALUES ('0', 'Jamaica');
INSERT INTO `origin_box` VALUES ('0', 'Japan');
INSERT INTO `origin_box` VALUES ('0', 'Korea');
INSERT INTO `origin_box` VALUES ('0', 'Mexico');
INSERT INTO `origin_box` VALUES ('0', 'Netherland');
INSERT INTO `origin_box` VALUES ('0', 'New Zealand');
INSERT INTO `origin_box` VALUES ('0', 'Peru');
INSERT INTO `origin_box` VALUES ('0', 'Philippines');
INSERT INTO `origin_box` VALUES ('0', 'Poland');
INSERT INTO `origin_box` VALUES ('0', 'Russia');
INSERT INTO `origin_box` VALUES ('0', 'Scottland');
INSERT INTO `origin_box` VALUES ('0', 'Singapore');
INSERT INTO `origin_box` VALUES ('0', 'Sweden');
INSERT INTO `origin_box` VALUES ('0', 'Swiss');
INSERT INTO `origin_box` VALUES ('0', 'USA');